# Use lightweight Node.js 20 base image (Alpine Linux)
FROM node:20-alpine

# Set working directory where the app will live inside the container
WORKDIR /app

# Run Node in production mode for better performance and leaner behavior
ENV NODE_ENV=production

# Define the port the app will listen on inside the container
ENV PORT=80

# Copy package manifests to leverage Docker layer caching for installs
COPY package.json package-lock.json ./

# Install only production dependencies according to the lockfile
RUN npm ci --omit=dev

# Copy prebuilt frontend assets generated by `npm run build`
COPY dist ./dist

# Copy the Node/Express server that serves the built assets and API
COPY server.js .

# Document that the container exposes port 80
EXPOSE 80

# Launch the Express server when the container starts
CMD ["node", "server.js"]
